### ISSUE TITLE
Andrew do you use discord? If not get it.

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Untitled-Game-Client#1]
I want to be able to easily collab with u, and discord also has a nice dev api, you should try it out.
add me SharkFin#0936

**Comment by Andrews54757** [comment]
@SharkFinPro This is a very complicated project with complicated things such as math. It is nice that you want to help me, but I think I can handle this myself.

Currently, I am just creating the spritesheet.

<img width="1156" alt="screen shot 2018-01-10 at 6 35 18 pm" src="https://user-images.githubusercontent.com/13282284/34801157-127dde68-f635-11e7-87a7-8435f31276bf.png">

**Comment by SharkFinPro** [comment]
Ok

**Comment by SharkFinPro** [comment]
I do believe I have more coding experience than u tho lol

**Comment by Andrews54757** [comment]
@SharkFinPro Ok, why dont you create your own game? I think it will be good!

**Comment by SharkFinPro** [comment]
Lol...can I revive ogarUL? Many miss it

**Comment by Andrews54757** [comment]
@SharkFinPro OgarUL is trashy code that should never be run again ... unless you want your computer to burn due to it's inefficiency.
